"""trust_link

Revision ID: 6b5b918dd6cc
Revises: 14ef613fc29b
Create Date: 2023-08-09 15:21:20.133986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5b918dd6cc'
down_revision = '14ef613fc29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trust_link',
    sa.Column('current_user_id', sa.Integer(), nullable=True),
    sa.Column('trusted_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trusted_user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trust_link')
    # ### end Alembic commands ###
