"""trust links

Revision ID: a4497ee1a328
Revises: 1e105c185375
Create Date: 2023-08-10 15:31:21.079297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4497ee1a328'
down_revision = '1e105c185375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trust_links',
    sa.Column('current_user_id', sa.Integer(), nullable=True),
    sa.Column('trusted_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trusted_user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trust_links')
    # ### end Alembic commands ###
